<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Inbox\BuildingBlocks.Inbox.Abstractions\BuildingBlocks.Inbox.Abstractions.csproj" />
      <ProjectReference Include="..\BuildingBlocks.Messaging.Abstractions\BuildingBlocks.Messaging.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.1" />
    </ItemGroup>

</Project>
