<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\BuildingBlocks.Core\BuildingBlocks.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Marten" Version="7.33.0" />
    </ItemGroup>

</Project>
