<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks.Messaging.MassTransit\BuildingBlocks.Messaging.MassTransit.csproj" />
        <ProjectReference Include="..\..\Inbox\BuildingBlocks.Inbox.Abstractions\BuildingBlocks.Inbox.Abstractions.csproj" />
    </ItemGroup>

</Project>
